#!/bin/bash

BASEDIR="/opt/minecraft"

VERSION_LOCAL=$(unzip -p $BASEDIR/server.jar META-INF/versions.list | awk '{ print $2 }')
echo "Current version: $VERSION_LOCAL"

MANIFEST=$(curl -s "https://piston-meta.mojang.com/mc/game/version_manifest.json")
LATEST=$(echo "$MANIFEST" | jq -r '.["latest"]["release"]')
if [[ "$LATEST" != "$VERSION_LOCAL" ]]; then
    echo "Re-starting to upgrade from $VERSION_LOCAL to $LATEST"
    systemctl stop minecraft
    systemctl start minecraft
else
    echo "System already at $LATEST, no upgrade needed"
fi
